### PR TITLE
Update to use Query class instead of parameters

### PR DESCRIPTION
**Pull request by akameco**
`
        String ncode,
        int limit,
        int sortOrder,
        String search,
        String notSearch,
        boolean targetTitle,
        boolean targetStory,
        boolean targetKeyword,
        boolean targetWriter,
        int time,
        int maxLength,
        int minLength,
        boolean end,
        boolean stop,
       boolean pickup
` → `Query`

Merge #21  before merging it.

### CODE REVIEW

**Comment by akameco** [comment]
With this change, it is easy to migrate to ViewModel using DataBinding.

**Comment by nshiba** [comment]
nice!

But this seems to be able to use `Parcelable` .

If possible, Can you try?

**Comment by nshiba** [comment]
やらなくてもいいです。それならこれをマージした後に私がやります。

**Comment by nshiba** [comment]
You do not have to do it. Then I will do after merging this.

**Comment by nshiba** [comment]
thanks!

**Pull request merged**
